export const pokemonTypes = [
  { value: "normal", label: "Normal", color: "#a8a77a" },
  { value: "fire", label: "Fuego", color: "#ee8130" },
  { value: "water", label: "Agua", color: "#6390f0" },
  { value: "electric", label: "Electrico", color: "#f7d02c" },
  { value: "grass", label: "Planta", color: "#7ac74c" },
  { value: "ice", label: "Hielo", color: "#5fb6b1" },
  { value: "fighting", label: "Lucha", color: "#c22e28" },
  { value: "poison", label: "Veneno", color: "#a33ea1" },
  { value: "ground", label: "Tierra", color: "#e2bf65" },
  { value: "flying", label: "Volador", color: "#a98ff3" },
  { value: "psychic", label: "Psiquico", color: "#f95587" },
  { value: "bug", label: "Insecto", color: "#a6b91a" },
  { value: "rock", label: "Roca", color: "#b6a136" },
  { value: "ghost", label: "Fantasma", color: "#735797" },
  { value: "dragon", label: "Dragon", color: "#6f35fc" },
  { value: "dark", label: "Siniestro", color: "#705746" },
  { value: "steel", label: "Acero", color: "#b7b7ce" },
  { value: "fairy", label: "Hada", color: "#d685ad" },
];