-- AlterTable
ALTER TABLE `collection` MODIFY `status` ENUM('CAUGHT', 'NOT_CAUGHT', 'RELEASED') NOT NULL DEFAULT 'CAUGHT';

-- AlterTable
ALTER TABLE `user` ADD COLUMN `role` ENUM('PROFESSOR', 'TRAINER') NOT NULL DEFAULT 'TRAINER';
